name: Update README with Latest Blog Posts (Python)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show README(before)
        run: |
          echo "===== README (before) ====="
          sed -n '1,120p' README.md || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser==6.0.11

      - name: Update README from RSS
        run: |
          python scripts/update_readme.py "https://yoonbitnara.github.io/feed.xml" 5 "yyyy-mm-dd"

      - name: Show git diff
        run: |
          echo "===== git diff ====="
          git diff || true

      - name: Commit & Push if changed
        run: |
          if ! git diff --quiet; then
            git config user.name "readme-bot"
            git config user.email "readme-bot@example.com"
            git add README.md
            git commit -m "docs: 최신 블로그 글 자동 갱신 (Python)"
            git push
          else
            echo "No changes."
          fi

      - name: Show README(after)
        run: |
          echo "===== README (after) ====="
          sed -n '1,120p' README.md || true
